theme: jekyll-theme-architect

# Site settings
title: Kai Blog             # 你的博客网站标题
SEOTitle: Hux Blog			    # 在后面会详细谈到
description: "Bluetooth, Developer Relations"    # 随便说点，描述一下

# SNS settings      
github_username: kaiser-ren     # 你的github账号
weibo_username: @kaiser_ren     # 你的微博账号，底部链接会自动更新的。

# Build settings
# paginate: 10              # 一页你准备放几篇文章